# Generated by Django 5.0.1 on 2024-03-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_register_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tit', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=40)),
                ('disc', models.CharField(max_length=60)),
                ('imag', models.ImageField(upload_to='../media')),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
