# Generated by Django 5.0.1 on 2024-03-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_slide_alter_register_email_alter_register_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='disc',
            field=models.CharField(max_length=200),
        ),
    ]
