# Generated by Django 5.0.1 on 2024-03-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0004_alter_slide_disc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='link',
            field=models.CharField(max_length=100),
        ),
    ]
