# Generated by Django 5.0.1 on 2024-03-26 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0005_alter_slide_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='slide',
        ),
    ]
