# Generated by Django 5.0.1 on 2024-03-26 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecommendPage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
        ),
    ]
